#!/bin/bash
#
# Test the OpenLDAP image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

set -exo nounset
shopt -s nullglob

IMAGE_NAME=${IMAGE_NAME:-openshift/openldap-2441-centos7-candidate}

CIDFILE_DIR=$(mktemp --suffix=openldap_test_cidfiles -d)

function cleanup() {
  for cidfile in $CIDFILE_DIR/* ; do
    CONTAINER=$(cat $cidfile)

    echo "Stopping and removing container $CONTAINER..."
    docker stop $CONTAINER
    exit_status=$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER)
    if [ "$exit_status" != "0" ]; then
      echo "Dumping logs for $CONTAINER"
      docker logs $CONTAINER
    fi
    docker rm $CONTAINER
    rm $cidfile
    echo "Done."
  done
  rmdir $CIDFILE_DIR
}
trap cleanup EXIT SIGINT

function get_cid() {
  local id="$1" ; shift || return 1
  echo $(cat "$CIDFILE_DIR/$id")
}

function get_container_ip() {
  local id="$1"
  docker inspect --format='{{.NetworkSettings.IPAddress}}' $(get_cid "$id")
}

function openldap_cmd() {
  url_encoded_base=dc%3Dexample%2Cdc%3Dcom #dc=example,dc=com
  curl "ldap://${CONTAINER_IP}:389/${url_encoded_base}?$@"
}

function test_connection() {
  local name=$1
  ip=$(get_container_ip $name)
  echo "  Testing OpenLDAP connection to $ip..."
  local max_attempts=20
  local sleep_time=2
  for i in $(seq $max_attempts); do
    echo "    Trying to connect..."
    set +e
    openldap_cmd "objectClass%3D*" #objectClass=*
    status=$?
    set -e
    if [ $status -eq 0 ]; then
      echo "  Success!"
      return 0
    fi
    sleep $sleep_time
  done
  echo "  Giving up: Failed to connect. Logs:"
  docker logs $(get_cid $name)
  return 1
}

function test_openldap() {
  echo "  Testing OpenLDAP"
  openldap_cmd "objectClass%3Dorganization" | grep -E "dc=example,dc=com" #objectClass=organization
  echo "  Success!"
}

function create_container() {
  local name=$1
  cidfile="$CIDFILE_DIR/$name"
  # create container with a cidfile in a directory for cleanup
  docker run ${DOCKER_ARGS:-} --cidfile $cidfile -d $IMAGE_NAME ${CONTAINER_ARGS:-}
  echo "Created container $(cat $cidfile)"
}


function run_tests() {
  local name=$1
  create_container $name
  CONTAINER_IP=$(get_container_ip $name)
  test_connection $name
  test_openldap $name
  echo "  Test Success!"
}

# Tests.
run_tests test_container_root
# Test with arbitrary uid for the container
DOCKER_ARGS="-u 12345" run_tests test_container_nonroot
